#!/usr/bin/env python3
"""Keep root SKILL.md in sync with plugin/skills/*/SKILL.md metadata.

The root SKILL.md is the standalone-prompt version — substantial hand-written
framing (intro, SCHEMA.md prose, architecture, pitfalls). We don't regenerate
that. What this script does:

1. Maintains an autogenerated skills table between markers in root SKILL.md.
2. Detects drift: every skill's name, version, description, and argument-hint
   from frontmatter must appear consistently in root SKILL.md.
3. `--check` exits nonzero on drift — wired into CI.

Usage:
    scripts/build_skill_md.py             # update the autogenerated block
    scripts/build_skill_md.py --check     # report drift, exit 1 if any
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROOT_SKILL = REPO / "SKILL.md"
SKILLS_DIR = REPO / "plugin" / "skills"

BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED skill-table -->"
END_MARKER = "<!-- END AUTOGENERATED skill-table -->"


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(.*)$", line)
        if not mm:
            continue
        key, val = mm.group(1), mm.group(2).strip()
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        elif val.startswith("'") and val.endswith("'"):
            val = val[1:-1]
        out[key] = val
    return out


def collect_skills() -> list[dict]:
    skills = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        text = skill_md.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if "name" not in fm:
            continue
        skills.append({
            "name": fm["name"],
            "description": fm.get("description", ""),
            "argument_hint": fm.get("argument-hint", ""),
            "path": skill_md.relative_to(REPO).as_posix(),
        })
    return skills


def render_table(skills: list[dict]) -> str:
    lines = [
        BEGIN_MARKER,
        "",
        "<!-- Generated by scripts/build_skill_md.py — do not edit manually. -->",
        "<!-- Source: plugin/skills/*/SKILL.md frontmatter. -->",
        "",
        "| Skill | Argument hint | Description |",
        "|-------|---------------|-------------|",
    ]
    for s in skills:
        desc = s["description"].replace("|", "\\|")
        hint = s["argument_hint"].replace("|", "\\|") or "—"
        lines.append(f"| `{s['name']}` | `{hint}` | {_truncate(desc, 100)} |")
    lines.extend(["", END_MARKER])
    return "\n".join(lines)


def _truncate(s: str, n: int) -> str:
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def update_block(skill_md_text: str, new_block: str) -> str:
    if BEGIN_MARKER in skill_md_text:
        pattern = re.compile(
            re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
            re.DOTALL,
        )
        return pattern.sub(new_block, skill_md_text)
    # Insert before the first "## Skills" section, or append at end if absent.
    skills_h = re.search(r"^## Skills\s*$", skill_md_text, re.MULTILINE)
    if skills_h:
        return (skill_md_text[:skills_h.start()] +
                new_block + "\n\n" +
                skill_md_text[skills_h.start():])
    return skill_md_text.rstrip() + "\n\n" + new_block + "\n"


def detect_drift(skills: list[dict], root_text: str) -> list[str]:
    """Detect *contradictions* between the per-skill files and root SKILL.md.

    The root is a curated summary, so we don't require argument-hints to
    appear verbatim — that's expected condensation, not drift. We flag only:

    1. A defined skill not mentioned in the root at all.
    2. The root mentioning a `wiki-*` skill that doesn't exist on disk.
    """
    drift = []
    for s in skills:
        if s["name"] not in root_text:
            drift.append(
                f"skill {s['name']!r} (defined in {s['path']}) not mentioned "
                f"in root SKILL.md")
    skill_names = {s["name"] for s in skills}
    found_in_root = set(re.findall(r"\bwiki-[a-z]+\b", root_text))
    extras = found_in_root - skill_names
    for name in extras:
        # `wiki-plugins` refers to .wiki-plugins.yaml, not a skill.
        if name in ("wiki-plugins",):
            continue
        drift.append(
            f"root SKILL.md mentions {name!r}, but no matching skill exists "
            f"under plugin/skills/")
    return drift


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="Report drift only; do not modify SKILL.md")
    args = p.parse_args()

    if not ROOT_SKILL.exists():
        print(f"FAIL: {ROOT_SKILL} not found", file=sys.stderr)
        return 2

    skills = collect_skills()
    if not skills:
        print(f"FAIL: no skills found under {SKILLS_DIR}", file=sys.stderr)
        return 2

    root_text = ROOT_SKILL.read_text(encoding="utf-8")

    drift = detect_drift(skills, root_text)
    new_block = render_table(skills)
    new_text = update_block(root_text, new_block)
    needs_write = new_text != root_text

    if args.check:
        problems = []
        problems.extend(drift)
        if needs_write:
            problems.append(
                "autogenerated skill-table block is out of date; run "
                "`python scripts/build_skill_md.py` to update.")
        if problems:
            for p_ in problems:
                print(f"DRIFT: {p_}")
            return 1
        print("ok: SKILL.md is in sync with plugin/skills/*/SKILL.md")
        return 0

    # Default: write the updated table.
    if needs_write:
        ROOT_SKILL.write_text(new_text, encoding="utf-8")
        print(f"updated skill-table block in {ROOT_SKILL.relative_to(REPO)}")
    else:
        print(f"no changes — {ROOT_SKILL.relative_to(REPO)} already in sync")

    if drift:
        print("\nDrift remaining (manual fix required):")
        for p_ in drift:
            print(f"  - {p_}")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
